// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZNvGt2-BH25hyuV3thATfajbdOgA9rs',
    appId: '1:680320260355:web:bc7a20f5aa44fa5076b136',
    messagingSenderId: '680320260355',
    projectId: 'thinksy-ed0fd',
    authDomain: 'thinksy-ed0fd.firebaseapp.com',
    storageBucket: 'thinksy-ed0fd.firebasestorage.app',
    measurementId: 'G-V362J3QPQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkt3u9CZKuy6goPSVsvg1Af2qSnmGATug',
    appId: '1:680320260355:android:4ad531ca65a93bb276b136',
    messagingSenderId: '680320260355',
    projectId: 'thinksy-ed0fd',
    storageBucket: 'thinksy-ed0fd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXZNvGt2-BH25hyuV3thATfajbdOgA9rs',
    appId: '1:680320260355:web:2a65a174b7cec0e576b136',
    messagingSenderId: '680320260355',
    projectId: 'thinksy-ed0fd',
    authDomain: 'thinksy-ed0fd.firebaseapp.com',
    storageBucket: 'thinksy-ed0fd.firebasestorage.app',
    measurementId: 'G-BLNJWZ745Q',
  );
}
